export type Minor = {
  id: string;
  title: string;
  tagline: string;
  tags: { label: string; color: "mint" | "orange" | "sun" | "indigo" }[];
  about: string;
  image: string; // gradient css
  docent: string;
  opleiding: string;
  thema: string;
  plaats: string;
  niveau: string;
  ec: number;
  taal: string;
  type: string;
  code: string;
  leerdoelen: string[];
  ingangseisen?: string;
  toetsing?: string;
  aanvullendeInfo?: string;
};

export const MINORS: Minor[] = [
  {
    id: "design-art",
    title: "Design art",
    tagline: "Geïnteresseerd in Art, Design en Technologie?",
    tags: [
      { label: "AI", color: "orange" },
      { label: "Programmeren", color: "mint" },
      { label: "Onderzoeken", color: "indigo" },
      { label: "Kunstacademie", color: "sun" },
    ],
    about:
      "Sluit je aan bij de Design Art Technology minor van Minerva Art Academy. Hier werken studenten uit verschillende disciplines samen aan werken die kunst, design en technologie combineren. Deze 30 ECTS module in artistieke technologieonderzoek is bedoeld voor tweedejaars studenten.\n\nStudenten uit alle richtingen zijn welkom — de mix van achtergronden creëert vruchtbare grond om op te groeien.",
    image: "linear-gradient(135deg, oklch(0.45 0.15 320), oklch(0.55 0.2 25))",
    docent: "Bjorn Eerkes",
    opleiding: "Autonome Beeldende Kunst",
    thema: "Kunstacademie",
    plaats: "Groningen",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Engels",
    type: "Minor",
    code: "MK26ABDAT",
    leerdoelen: ["Praktijkervaring", "Specialiseren", "Creativiteit"],
    ingangseisen: "De minor is open voor alle derdejaars studenten van Hanze Hogeschool of Minerva Art Academy. Je doorloopt een intakeprocedure.",
    toetsing: "De minor bestaat uit verschillende skill labs gecombineerd met workshops. Theorie in art, design en tech is essentieel. Er zijn 2 toetsen en een essay vereist.",
    aanvullendeInfo: "Je moet worden toegelaten tot deze minor. Na inschrijving neemt de coördinator contact met je op.",
  },
  {
    id: "motion-graphics",
    title: "Motion graphics",
    tagline: "Geïnteresseerd in Art, Design en Technologie?",
    tags: [
      { label: "AI", color: "orange" },
      { label: "Programmeren", color: "mint" },
    ],
    about:
      "Breng verhalen tot leven via geanimeteerde typografie, kinetische identiteit en interactieve videosystemen. Je collaboreert met verschillende disciplines om beweging te ontwerpen voor schermen in elke grootte.",
    image: "linear-gradient(135deg, oklch(0.6 0.22 30), oklch(0.55 0.2 280))",
    docent: "Lotte de Jong",
    opleiding: "Communication & Multimedia Design",
    thema: "Visuele communicatie",
    plaats: "Groningen",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Engels",
    type: "Minor",
    code: "MK26CMDMG",
    leerdoelen: ["Creativiteit", "Technische skills"],
    ingangseisen: "Voorkeur voor studenten uit Communication & Multimedia Design of vergelijkbare programma's. Ervaring met video-editing is nuttig maar niet vereist.",
    toetsing: "Beoordeling van portfolio, presentatie van motion graphics projecten en praktische opdrachten met focus op technische vaardigheid.",
    aanvullendeInfo: "Toegang tot professionele software en apparatuur. Regelmatige feedbacksessies met professionals uit de industrie.",
  },
  {
    id: "data-storytelling",
    title: "Data storytelling",
    tagline: "Maak van cijfers betekenis",
    tags: [
      { label: "Onderzoeken", color: "indigo" },
      { label: "Storytelling", color: "sun" },
    ],
    about:
      "Leer ruwe datasets vertalen naar heldere, persoonlijke verhalen. Combineer journalistieke nieuwsgierigheid met visualisatie en narratief design.",
    image: "linear-gradient(135deg, oklch(0.45 0.18 250), oklch(0.7 0.16 80))",
    docent: "Sanne Vermeer",
    opleiding: "Communicatie",
    thema: "Onderzoek & journalistiek",
    plaats: "Groningen",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Nederlands",
    type: "Minor",
    code: "MK26COMDS",
    leerdoelen: ["Onderzoeken", "Schrijven", "Visualiseren"],
    ingangseisen: "Basiskennis van statistiek is nuttig. Open voor alle studenten die interesse hebben in data-gedreven storytelling.",
    toetsing: "Afronding van datavisualisatieprojecten, schriftelijke analyse van casestudies en een eindportfolio met demonstratie van vaardigheid.",
    aanvullendeInfo: "Tools als Tableau, Excel en design software worden aangeboden. Gastspreken van journalisten en visualisatiespecialisten.",
  },
  {
    id: "smart-cities",
    title: "Smart cities",
    tagline: "Bouw aan de stad van morgen",
    tags: [
      { label: "Strategie", color: "indigo" },
      { label: "Onderzoeken", color: "mint" },
      { label: "Branding", color: "orange" },
    ],
    about:
      "Een interdisciplinaire minor waar tech, beleid en stedelijke vraagstukken samenkomen. Werk aan échte cases met gemeentes en bewoners.",
    image: "linear-gradient(135deg, oklch(0.5 0.12 200), oklch(0.7 0.15 140))",
    docent: "Pieter Klaassen",
    opleiding: "Built Environment",
    thema: "Stedelijke innovatie",
    plaats: "Groningen",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Nederlands",
    type: "Minor",
    code: "MK26BESMC",
    leerdoelen: ["Samenwerken", "Onderzoeken"],
    ingangseisen: "Open voor alle studenten geïnteresseerd in stedelijke vraagstukken en innovatie. Geen specifieke voorkennis vereist, maar achtergrond in stedenbouw of technologie is waardevol.",
    toetsing: "Uitvoering van groepsproject met echte stakeholders, presentatie van bevindingen en reflectieessay over innovatieproces.",
    aanvullendeInfo: "Samenwerkingen met echte steden en gemeentes. Gastlezingen van stedenbouwers en beleidsmakers. Potentie om projecten daadwerkelijk in gemeenten ingevoerd te zien.",
  },
  {
    id: "game-worlds",
    title: "Game worlds",
    tagline: "Ontwerp werelden waar spelers in geloven",
    tags: [
      { label: "Game design", color: "orange" },
      { label: "Programmeren", color: "mint" },
    ],
    about:
      "Van level-design tot narrative systems. Bouw speelbare prototypes en leer hoe je spelers raakt — emotioneel én mechanisch.",
    image: "linear-gradient(135deg, oklch(0.4 0.18 290), oklch(0.7 0.2 50))",
    docent: "Kim Bakker",
    opleiding: "Game Development",
    thema: "Game & interactie",
    plaats: "Groningen",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Engels",
    type: "Minor",
    code: "MK26GDGW",
    leerdoelen: ["Creativiteit", "Prototypen"],
    ingangseisen: "Ervaring met game engines als Unity of Unreal is nuttig. Basiskennis van game design-principes vereist of bereidheid snel te leren.",
    toetsing: "Indiening van speelbaar gameprototype met designdocumentatie, integratie van feedback van peers en presentatie van gameconcept.",
    aanvullendeInfo: "Volledige toegang tot game development labs met krachtige computers. Mentorschap van professionele game developers. Mogelijkheid om games op industriegebeurtenissen te tonen.",
  },
  {
    id: "sustainable-innovation",
    title: "Sustainable Innovation",
    tagline: "Duurzame oplossingen voor morgen",
    tags: [
      { label: "Onderzoeken", color: "indigo" },
      { label: "Strategie", color: "sun" },
      { label: "Ondernemerschap", color: "orange" },
    ],
    about:
      "Ontdek hoe je duurzame projecten kunt initiëren en schalen. Van conceptontwikkeling tot marktintroductie. Werk samen met bedrijven en NGO's aan échte cases.",
    image: "linear-gradient(135deg, oklch(0.5 0.18 140), oklch(0.65 0.15 100))",
    docent: "Maria Groenveld",
    opleiding: "Bedrijfskunde",
    thema: "Duurzaamheid & innovatie",
    plaats: "Zwolle",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Nederlands",
    type: "Minor",
    code: "HZ26BKSI",
    leerdoelen: ["Ondernemerschap", "Duurzaamheid", "Innovatiemethodologie"],
    ingangseisen: "Open voor alle studenten. Basiskennis van bedrijfsvoering en duurzaamheid is nuttig, maar niet verplicht.",
    toetsing: "Ontwikkeling van businessplan, impactrapportage, pitchpresentatie en reflectie op projectuitvoering.",
    aanvullendeInfo: "Directe verbindingen met sociale ondernemingen en duurzaamheidsinnovatoren. Financieringsmogelijkheden voor veelbelovende projecten. Toegang tot ondernemingsondersteunersnetwerk.",
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing & Content",
    tagline: "Bouw je online presence",
    tags: [
      { label: "Marketing", color: "orange" },
      { label: "Storytelling", color: "sun" },
      { label: "Onderzoeken", color: "indigo" },
    ],
    about:
      "Leer strategische en tactische digital marketing: SEO, social media, content strategy en data-driven campaigns. Werk met echte klanten en merk je impact.",
    image: "linear-gradient(135deg, oklch(0.55 0.2 25), oklch(0.6 0.18 280))",
    docent: "Tom Jansen",
    opleiding: "Marketing Communication",
    thema: "Digital & strategie",
    plaats: "Leeuwarden",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Nederlands",
    type: "Minor",
    code: "HZ26MKDM",
    leerdoelen: ["Digital strategy", "Analytics", "Content creation"],
    ingangseisen: "Basiskennis van social media en digitale tools is nuttig. Studenten uit alle disciplines welkom.",
    toetsing: "Campaign strategy document, content calendar, analytics rapportage en live campaign presentatie.",
    aanvullendeInfo: "Echte klantprojecten voor portfoliobouw. Tools: Google Analytics, Hootsuite, Canva Pro. Maandelijkse gastlezingen van experts.",
  },
  {
    id: "interaction-design",
    title: "Interaction Design",
    tagline: "Maak gebruiksvriendelijke ervaringen",
    tags: [
      { label: "UX/UI", color: "mint" },
      { label: "Programmeren", color: "orange" },
      { label: "Onderzoeken", color: "indigo" },
    ],
    about:
      "Ontwerp interactieve digitale producten met focus op user experience. Van research tot prototype. Leer hoe gebruikers echt denken en waarom design-keuzes tellen.",
    image: "linear-gradient(135deg, oklch(0.5 0.16 200), oklch(0.6 0.2 30))",
    docent: "Linda Martens",
    opleiding: "Communication & Multimedia Design",
    thema: "Digital design",
    plaats: "Groningen",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Engels",
    type: "Minor",
    code: "HZ26CMID",
    leerdoelen: ["UX research", "Prototyping", "User testing"],
    ingangseisen: "Interesse in design en gebruikersgedrag. Basiskennis van design software is nuttig. Programmeerkennis niet vereist.",
    toetsing: "UX research casestudy, interactief prototype, usability testing rapportage en designpresentatie.",
    aanvullendeInfo: "Toegang tot designtools: Figma, Adobe XD, Sketch. User testing lab. Samenwerking met digitale bureaus aan echte projecten.",
  },
  {
    id: "data-science-basics",
    title: "Data Science Essentials",
    tagline: "Van data naar inzichten",
    tags: [
      { label: "Programmeren", color: "mint" },
      { label: "Onderzoeken", color: "indigo" },
      { label: "Analyse", color: "orange" },
    ],
    about:
      "Leer de fundamentals van data science: data wrangling, visualisatie en basis machine learning. Werk met echte datasets en bouw predictive models.",
    image: "linear-gradient(135deg, oklch(0.4 0.2 240), oklch(0.65 0.18 200))",
    docent: "Robert Verschelling",
    opleiding: "Informatica",
    thema: "Data & AI",
    plaats: "Leeuwarden",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Engels",
    type: "Minor",
    code: "HZ26ITDS",
    leerdoelen: ["Python programming", "Data analysis", "Machine learning basics"],
    ingangseisen: "Basiskennis programmeren of bereidheid snel te leren. Wiskundige basis is nuttig.",
    toetsing: "Data analysis project met rapport, machine learning model development, inzichtenpresentatie en codedocumentatie.",
    aanvullendeInfo: "Python, R en SQL onderwezen. Jupyter notebooks en Kaggle datasets. Mentorschap van data professionals. Gastlezingen over industrietoepassingen.",
  },
  {
    id: "social-entrepreneurship",
    title: "Ondernemen",
    tagline: "Ondernemen met maatschappelijk impact",
    tags: [
      { label: "Ondernemerschap", color: "orange" },
      { label: "Samenwerken", color: "sun" },
      { label: "Strategie", color: "indigo" },
    ],
    about:
      "Start je eigen sociale onderneming of verbeter bestaande. Focus op impact measurement, stakeholder engagement en business model innovation voor goede doelen.",
    image: "linear-gradient(135deg, oklch(0.45 0.18 80), oklch(0.6 0.16 150))",
    docent: "Sophie Adriaansen",
    opleiding: "Maatschappelijk Werk & Dienstverlening",
    thema: "Impact & innovation",
    plaats: "Rotterdam",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Nederlands",
    type: "Minor",
    code: "AV26MWSE",
    leerdoelen: ["Impact strategy", "Stakeholder management", "Business planning"],
    ingangseisen: "Open voor alle studenten. Passie voor maatschappelijk impact is belangrijker dan voorkennis.",
    toetsing: "Businessplan voor sociale onderneming, impact measurement framework, geïnterviewde stakeholders documentatie en pitchpresentatie.",
    aanvullendeInfo: "Toegang tot netwerk van sociale ondernemers. Mentorschap van ervaren social entrepreneurs. Financieringsverbindingen voor levensvatbare projecten.",
  },
  {
    id: "creative-technology",
    title: "Creatieve technologie",
    tagline: "Kunst en techniek samenbrengen",
    tags: [
      { label: "Programmeren", color: "mint" },
      { label: "Creativiteit", color: "orange" },
      { label: "Interactie", color: "sun" },
    ],
    about:
      "Maak immersive installaties en interactive art. Werk met Arduino, 3D printing, AR/VR. Combineer code, design en kunstenaarschap in experimentele projecten.",
    image: "linear-gradient(135deg, oklch(0.35 0.22 300), oklch(0.7 0.2 40))",
    docent: "Marcus van den Berg",
    opleiding: "Fine Arts Technology",
    thema: "Art & interaction",
    plaats: "Arnhem",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Engels",
    type: "Minor",
    code: "AV26FATC",
    leerdoelen: ["Creative coding", "Physical computing", "Installation design"],
    ingangseisen: "Interesse in kunst en technologie. Enige programmeer- of maakervaring is nuttig maar niet vereist.",
    toetsing: "Ontwikkeling van interactief kunstwerk, documentatie van creatief proces, technische presentatie en tentoonstelling in galerie.",
    aanvullendeInfo: "Volledige toegang tot makerspace met 3D-printers, laser cutters en elektronicalab. Mentorschap van mediakunstenaars. Tentoonstellingsmogelijkheden.",
  },
  {
    id: "healthcare-innovation",
    title: "Gezondheidszorg innovatie",
    tagline: "Zorg van de toekomst ontwerpen",
    tags: [
      { label: "Onderzoeken", color: "indigo" },
      { label: "Design", color: "mint" },
      { label: "Innovatie", color: "orange" },
    ],
    about:
      "Tackle healthcare challenges door design thinking en co-creation toe te passen. Werk met patiënten, artsen en technologen aan praktische oplossingen.",
    image: "linear-gradient(135deg, oklch(0.5 0.18 10), oklch(0.65 0.2 350))",
    docent: "Dr. Anna Wolfers",
    opleiding: "Health & Social Care",
    thema: "Healthcare & technology",
    plaats: "Leeuwarden",
    niveau: "HBO-bachelor",
    ec: 30,
    taal: "Nederlands",
    type: "Minor",
    code: "HZ26HSHE",
    leerdoelen: ["Design thinking", "Healthcare insights", "Prototyping for health"],
    ingangseisen: "Interesse in healthcare challenges. Open voor alle studenten. Medische achtergrond niet vereist.",
    toetsing: "Gebruikersonderzoeksrapport, prototype development, feedback documentatie van healthcare stakeholders en solution presentatie.",
    aanvullendeInfo: "Samenwerkingen met ziekenhuizen en zorginstellingen. Echte patiëntbetrokkenheid in designproces. Toegang tot healthcare design resources.",
  },
];

export const SUGGESTIONS = {
  interesses: ["AI", "Onderzoeken", "Storytelling", "Programmeren", "Branding", "Strategie", "Game design", "Animatie", "Fotografie", "UX/UI", "Duurzaamheid", "Ondernemerschap", "Social impact"],
  skills: ["Onderzoeken", "Presenteren", "Organiseren", "Samenwerken", "Programmeren", "Analyseren", "Schrijven", "Testen", "Prototyperen", "Design", "Leadership", "Probleem oplossen"],
  leerdoelen: ["Praktijkervaring", "Technische skills", "Samenwerken met bedrijven", "Specialiseren", "Netwerken", "Organiseren", "Testen", "Ondernemerschap", "User research", "Innovation"],
  motivatie: ["Portfolio opbouwen", "Uitdaging", "Duidelijke structuur", "Creatief zijn", "Samenwerken", "Hands-on leren", "Theoretische diepgang", "Real world projects", "Impact maken"],
};
