/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerkenIntroRouteImport } from './routes/verken-intro'
import { Route as VerkenRouteImport } from './routes/verken'
import { Route as VergelijkenRouteImport } from './routes/vergelijken'
import { Route as StartModeRouteImport } from './routes/start-mode'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as RealityCheckRouteImport } from './routes/reality-check'
import { Route as ProfielRouteImport } from './routes/profiel'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizSkillsRouteImport } from './routes/quiz.skills'
import { Route as QuizOverviewRouteImport } from './routes/quiz.overview'
import { Route as QuizMotivatieRouteImport } from './routes/quiz.motivatie'
import { Route as QuizLeerdoelenRouteImport } from './routes/quiz.leerdoelen'
import { Route as QuizInteressesRouteImport } from './routes/quiz.interesses'
import { Route as MinorIdRouteImport } from './routes/minor.$id'

const VerkenIntroRoute = VerkenIntroRouteImport.update({
  id: '/verken-intro',
  path: '/verken-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const VerkenRoute = VerkenRouteImport.update({
  id: '/verken',
  path: '/verken',
  getParentRoute: () => rootRouteImport,
} as any)
const VergelijkenRoute = VergelijkenRouteImport.update({
  id: '/vergelijken',
  path: '/vergelijken',
  getParentRoute: () => rootRouteImport,
} as any)
const StartModeRoute = StartModeRouteImport.update({
  id: '/start-mode',
  path: '/start-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RealityCheckRoute = RealityCheckRouteImport.update({
  id: '/reality-check',
  path: '/reality-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfielRoute = ProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSkillsRoute = QuizSkillsRouteImport.update({
  id: '/quiz/skills',
  path: '/quiz/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizOverviewRoute = QuizOverviewRouteImport.update({
  id: '/quiz/overview',
  path: '/quiz/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizMotivatieRoute = QuizMotivatieRouteImport.update({
  id: '/quiz/motivatie',
  path: '/quiz/motivatie',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizLeerdoelenRoute = QuizLeerdoelenRouteImport.update({
  id: '/quiz/leerdoelen',
  path: '/quiz/leerdoelen',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizInteressesRoute = QuizInteressesRouteImport.update({
  id: '/quiz/interesses',
  path: '/quiz/interesses',
  getParentRoute: () => rootRouteImport,
} as any)
const MinorIdRoute = MinorIdRouteImport.update({
  id: '/minor/$id',
  path: '/minor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profiel': typeof ProfielRoute
  '/reality-check': typeof RealityCheckRoute
  '/shortlist': typeof ShortlistRoute
  '/start-mode': typeof StartModeRoute
  '/vergelijken': typeof VergelijkenRoute
  '/verken': typeof VerkenRoute
  '/verken-intro': typeof VerkenIntroRoute
  '/minor/$id': typeof MinorIdRoute
  '/quiz/interesses': typeof QuizInteressesRoute
  '/quiz/leerdoelen': typeof QuizLeerdoelenRoute
  '/quiz/motivatie': typeof QuizMotivatieRoute
  '/quiz/overview': typeof QuizOverviewRoute
  '/quiz/skills': typeof QuizSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profiel': typeof ProfielRoute
  '/reality-check': typeof RealityCheckRoute
  '/shortlist': typeof ShortlistRoute
  '/start-mode': typeof StartModeRoute
  '/vergelijken': typeof VergelijkenRoute
  '/verken': typeof VerkenRoute
  '/verken-intro': typeof VerkenIntroRoute
  '/minor/$id': typeof MinorIdRoute
  '/quiz/interesses': typeof QuizInteressesRoute
  '/quiz/leerdoelen': typeof QuizLeerdoelenRoute
  '/quiz/motivatie': typeof QuizMotivatieRoute
  '/quiz/overview': typeof QuizOverviewRoute
  '/quiz/skills': typeof QuizSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profiel': typeof ProfielRoute
  '/reality-check': typeof RealityCheckRoute
  '/shortlist': typeof ShortlistRoute
  '/start-mode': typeof StartModeRoute
  '/vergelijken': typeof VergelijkenRoute
  '/verken': typeof VerkenRoute
  '/verken-intro': typeof VerkenIntroRoute
  '/minor/$id': typeof MinorIdRoute
  '/quiz/interesses': typeof QuizInteressesRoute
  '/quiz/leerdoelen': typeof QuizLeerdoelenRoute
  '/quiz/motivatie': typeof QuizMotivatieRoute
  '/quiz/overview': typeof QuizOverviewRoute
  '/quiz/skills': typeof QuizSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/profiel'
    | '/reality-check'
    | '/shortlist'
    | '/start-mode'
    | '/vergelijken'
    | '/verken'
    | '/verken-intro'
    | '/minor/$id'
    | '/quiz/interesses'
    | '/quiz/leerdoelen'
    | '/quiz/motivatie'
    | '/quiz/overview'
    | '/quiz/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/profiel'
    | '/reality-check'
    | '/shortlist'
    | '/start-mode'
    | '/vergelijken'
    | '/verken'
    | '/verken-intro'
    | '/minor/$id'
    | '/quiz/interesses'
    | '/quiz/leerdoelen'
    | '/quiz/motivatie'
    | '/quiz/overview'
    | '/quiz/skills'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/profiel'
    | '/reality-check'
    | '/shortlist'
    | '/start-mode'
    | '/vergelijken'
    | '/verken'
    | '/verken-intro'
    | '/minor/$id'
    | '/quiz/interesses'
    | '/quiz/leerdoelen'
    | '/quiz/motivatie'
    | '/quiz/overview'
    | '/quiz/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfielRoute: typeof ProfielRoute
  RealityCheckRoute: typeof RealityCheckRoute
  ShortlistRoute: typeof ShortlistRoute
  StartModeRoute: typeof StartModeRoute
  VergelijkenRoute: typeof VergelijkenRoute
  VerkenRoute: typeof VerkenRoute
  VerkenIntroRoute: typeof VerkenIntroRoute
  MinorIdRoute: typeof MinorIdRoute
  QuizInteressesRoute: typeof QuizInteressesRoute
  QuizLeerdoelenRoute: typeof QuizLeerdoelenRoute
  QuizMotivatieRoute: typeof QuizMotivatieRoute
  QuizOverviewRoute: typeof QuizOverviewRoute
  QuizSkillsRoute: typeof QuizSkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verken-intro': {
      id: '/verken-intro'
      path: '/verken-intro'
      fullPath: '/verken-intro'
      preLoaderRoute: typeof VerkenIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verken': {
      id: '/verken'
      path: '/verken'
      fullPath: '/verken'
      preLoaderRoute: typeof VerkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vergelijken': {
      id: '/vergelijken'
      path: '/vergelijken'
      fullPath: '/vergelijken'
      preLoaderRoute: typeof VergelijkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-mode': {
      id: '/start-mode'
      path: '/start-mode'
      fullPath: '/start-mode'
      preLoaderRoute: typeof StartModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reality-check': {
      id: '/reality-check'
      path: '/reality-check'
      fullPath: '/reality-check'
      preLoaderRoute: typeof RealityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiel': {
      id: '/profiel'
      path: '/profiel'
      fullPath: '/profiel'
      preLoaderRoute: typeof ProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/skills': {
      id: '/quiz/skills'
      path: '/quiz/skills'
      fullPath: '/quiz/skills'
      preLoaderRoute: typeof QuizSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/overview': {
      id: '/quiz/overview'
      path: '/quiz/overview'
      fullPath: '/quiz/overview'
      preLoaderRoute: typeof QuizOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/motivatie': {
      id: '/quiz/motivatie'
      path: '/quiz/motivatie'
      fullPath: '/quiz/motivatie'
      preLoaderRoute: typeof QuizMotivatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/leerdoelen': {
      id: '/quiz/leerdoelen'
      path: '/quiz/leerdoelen'
      fullPath: '/quiz/leerdoelen'
      preLoaderRoute: typeof QuizLeerdoelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/interesses': {
      id: '/quiz/interesses'
      path: '/quiz/interesses'
      fullPath: '/quiz/interesses'
      preLoaderRoute: typeof QuizInteressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minor/$id': {
      id: '/minor/$id'
      path: '/minor/$id'
      fullPath: '/minor/$id'
      preLoaderRoute: typeof MinorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ProfielRoute: ProfielRoute,
  RealityCheckRoute: RealityCheckRoute,
  ShortlistRoute: ShortlistRoute,
  StartModeRoute: StartModeRoute,
  VergelijkenRoute: VergelijkenRoute,
  VerkenRoute: VerkenRoute,
  VerkenIntroRoute: VerkenIntroRoute,
  MinorIdRoute: MinorIdRoute,
  QuizInteressesRoute: QuizInteressesRoute,
  QuizLeerdoelenRoute: QuizLeerdoelenRoute,
  QuizMotivatieRoute: QuizMotivatieRoute,
  QuizOverviewRoute: QuizOverviewRoute,
  QuizSkillsRoute: QuizSkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
